import React from 'react'
import { NavbarLayout } from './navbar'
import { Footer } from './footer'
import Head from 'next/head';

const Layout = ({ children }) => {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />

                {/* bootstrap */}
                <link
                    rel="stylesheet"
                    href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
                    integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
                    crossorigin="anonymous"
                />
            </Head>
            <div>
                <NavbarLayout />
                <main> {children} </main>
                <Footer />
            </div>
        </>
    )
}

export default Layout